### ISSUE TITLE
zsh: killed     cgapp create

### ISSUE THREAD

**Issue by RazaShabbir03** [create-go-app/fiber-go-template#135]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the repository's issues section similar bug.
- [x] I understand, this is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`Mac OS`):
- Golang (`go1.18.3 darwin/arm64`):

**Describe the bug:**

I get this error when I use this command 'cgapp create'
The error is : zsh: killed cgapp create.

I used brew to install this package.

**Comment by koddr** [comment]
Hi,

I don't know how your system was configured, but try to check your brew installation (maybe `brew doctor` helps). At my side, everything is working fine via brew installation. 

Another way is try to install via regular Golang install.
