### ISSUE TITLE
os.Interrupt does not respond to Ctrl+C after fiber get some requests

### ISSUE THREAD

**Issue by boskiv** [create-go-app/fiber-go-template#90]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the repository's issues section similar bug.
- [x] I understand, this is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): `Darwin us2-al-004.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64 (macOS Monterey 12.0.1 (21A559))`
- Golang (`go version`): `go version go1.17.2 darwin/amd64`

**Describe the bug:**

**Steps to reproduce the behavior:**

1. Run App with `StartServerWithGracefulShutdown`
2. Get few requests
2. Press Ctrl+C
4. App does not exit

**Expected behavior:**

App should respond to Ctrl+C

**Screenshots:**
![Screen Shot 2021-11-24 at 11 52 00](https://user-images.githubusercontent.com/1939783/143290892-0d5450fd-149a-411e-b403-cb4508808e8f.png)

**Additional context:**
If I run Ctrl+C before any requests are served, it works as expected
![Screen Shot 2021-11-24 at 11 52 21](https://user-images.githubusercontent.com/1939783/143290964-87eea78e-16ba-4f6a-8941-97a499ff0977.png)

**Comment by boskiv** [comment]
FYI, this example also has an issue in my env `https://github.com/gofiber/recipes/blob/master/graceful-shutdown/main.go`

**Comment by boskiv** [comment]
After some experiments around ab and curl, i have idea that connection is holding by browser. After I close a browser server immediately exit. More then, time is different between firefox and chrome browsers. Firefox closing connection faster.
So I think you can close this issue, because gracefull exit works as expected.

**Comment by koddr** [comment]
Hi, @boskiv 

Yes it is. Graceful shot down doesn't close connection, if any client idle. If you don't want to, you can switch to `dev` in your dot env file.
